//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI_850.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDI_850.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code produit.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de déterminer l&apos;adresse de facturation pour le client .
        /// </summary>
        internal static string CustBTNotFound {
            get {
                return ResourceManager.GetString("CustBTNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code client.
        /// </summary>
        internal static string CustomerItemId {
            get {
                return ResourceManager.GetString("CustomerItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de déterminer l&apos;adresse de livraison pour le client .
        /// </summary>
        internal static string CustSTNotFound {
            get {
                return ResourceManager.GetString("CustSTNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De la validation des données du client.
        /// </summary>
        internal static string CustVal {
            get {
                return ResourceManager.GetString("CustVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de déterminer l&apos;escompte du client. L&apos;escompte a été mis à 0%.
        /// </summary>
        internal static string DiscountNotFound {
            get {
                return ResourceManager.GetString("DiscountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;a pas été possible de déterminer le No. de produit d&apos;Enveloppes Laurentides à partir du code du client.
        /// </summary>
        internal static string ELCodeNotFound {
            get {
                return ResourceManager.GetString("ELCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultats de validation pour bon de commande #.
        /// </summary>
        internal static string EmailHeader {
            get {
                return ResourceManager.GetString("EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # de commande vide dans fichier EDI.
        /// </summary>
        internal static string EmptyPO {
            get {
                return ResourceManager.GetString("EmptyPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel EDI pour client.
        /// </summary>
        internal static string ExternalEmailSubject {
            get {
                return ResourceManager.GetString("ExternalEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel EDI pour bureau des commandes.
        /// </summary>
        internal static string InternalEmailSubject {
            get {
                return ResourceManager.GetString("InternalEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Id client invalide.
        /// </summary>
        internal static string InvalidCustId {
            get {
                return ResourceManager.GetString("InvalidCustId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas retouvée.
        /// </summary>
        internal static string ItemStatusNotFound {
            get {
                return ResourceManager.GetString("ItemStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manque inventaire.
        /// </summary>
        internal static string ItemStatusNotInStock {
            get {
                return ResourceManager.GetString("ItemStatusNotInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De la validation des données des items de la commande.
        /// </summary>
        internal static string ItemVal {
            get {
                return ResourceManager.GetString("ItemVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La nouvelle addresse est:.
        /// </summary>
        internal static string NewSTAddress {
            get {
                return ResourceManager.GetString("NewSTAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De la validation des données de la commande.
        /// </summary>
        internal static string OrderVal {
            get {
                return ResourceManager.GetString("OrderVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prix de palette est zéro. SVP valider..
        /// </summary>
        internal static string PalletPriceNotFound {
            get {
                return ResourceManager.GetString("PalletPriceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La qté palette est à zéro. SVP valider..
        /// </summary>
        internal static string PalletQtyZero {
            get {
                return ResourceManager.GetString("PalletQtyZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date du bon de commande ne correspond pas à la date de réception EDI.
        /// </summary>
        internal static string PODateMismatch {
            get {
                return ResourceManager.GetString("PODateMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correspond à la date d&apos;aujourd&apos;hui. SVP valider si urgence.
        /// </summary>
        internal static string PODateToday {
            get {
                return ResourceManager.GetString("PODateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est une date passée. SVP vérifier avec le client.
        /// </summary>
        internal static string POInPast {
            get {
                return ResourceManager.GetString("POInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date requise dans la commande.
        /// </summary>
        internal static string POReqDate {
            get {
                return ResourceManager.GetString("POReqDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0}: Le prix pour cet item est différent de notre prix. Nous utilisons {1:C2} au lieu de {2:C2}.
        /// </summary>
        internal static string PriceDiff {
            get {
                return ResourceManager.GetString("PriceDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de déterminer le prix de cet item. Le prix a été mis à $0.00.
        /// </summary>
        internal static string PriceNotFound {
            get {
                return ResourceManager.GetString("PriceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code de produit.
        /// </summary>
        internal static string ProdCode {
            get {
                return ResourceManager.GetString("ProdCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code d&apos;Enveloppes Laurentides n&apos;est pas fourni par le client.
        /// </summary>
        internal static string ProdCodeEmpty {
            get {
                return ResourceManager.GetString("ProdCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;item du code d&apos;Enveloppes Laurentides ne correspond pas a l&apos;item du code client.
        /// </summary>
        internal static string ProdCodeNoMatch {
            get {
                return ResourceManager.GetString("ProdCodeNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code client n&apos;est pas fourni par le client.
        /// </summary>
        internal static string ProdCustCodeEmpty {
            get {
                return ResourceManager.GetString("ProdCustCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;item n&apos;a pas été trouvé avec le code d&apos;Enveloppes Laurentides fourni par le client.
        /// </summary>
        internal static string ProdNotFound {
            get {
                return ResourceManager.GetString("ProdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qté.
        /// </summary>
        internal static string Quant {
            get {
                return ResourceManager.GetString("Quant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;expédition requise.
        /// </summary>
        internal static string ReqShipDate {
            get {
                return ResourceManager.GetString("ReqShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de livraison.
        /// </summary>
        internal static string ShipTo {
            get {
                return ResourceManager.GetString("ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français (défaut).
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utilisation de l&apos;adresse de facturation.
        /// </summary>
        internal static string UseBT {
            get {
                return ResourceManager.GetString("UseBT", resourceCulture);
            }
        }
    }
}
