using System;

namespace vivael
{
	public class data_ivprod : DataSource
	{
		public data_ivprod() { Table_name = i.name = "ivprod"; i.primary_1 = "ident"; i.primary_2 = null; i.primary_3 = null; isFoxpro = true; }

		private int _Ident; public int Ident { get { return _Ident; } set { Set(ref _Ident, value, "Ident"); } }
		private string _Code; public string Code { get { return _Code; } set { Set(ref _Code, value, "Code"); } }
		private string _Desc; public string Desc { get { return _Desc; } set { Set(ref _Desc, value, "Desc"); } }
		private string _Descl2; public string Descl2 { get { return _Descl2; } set { Set(ref _Descl2, value, "Descl2"); } }
		private int? _Idtype; public int? Idtype { get { return _Idtype; } set { Set(ref _Idtype, value, "Idtype"); } }
		private int? _Idclient; public int? Idclient { get { return _Idclient; } set { Set(ref _Idclient, value, "Idclient"); } }
		private int? _Idsupplier; public int? Idsupplier { get { return _Idsupplier; } set { Set(ref _Idsupplier, value, "Idsupplier"); } }
		private int? _Category; public int? Category { get { return _Category; } set { Set(ref _Category, value, "Category"); } }
		private string _Codesupp; public string Codesupp { get { return _Codesupp; } set { Set(ref _Codesupp, value, "Codesupp"); } }
		private int? _Qtyctns; public int? Qtyctns { get { return _Qtyctns; } set { Set(ref _Qtyctns, value, "Qtyctns"); } }
		private byte? _Lifespan; public byte? Lifespan { get { return _Lifespan; } set { Set(ref _Lifespan, value, "Lifespan"); } }
		private decimal? _Ac_Tot_Mnt; public decimal? Ac_Tot_Mnt { get { return _Ac_Tot_Mnt; } set { Set(ref _Ac_Tot_Mnt, value, "Ac_Tot_Mnt"); } }
		private decimal? _Ac_Tot_Mnt2; public decimal? Ac_Tot_Mnt2 { get { return _Ac_Tot_Mnt2; } set { Set(ref _Ac_Tot_Mnt2, value, "Ac_Tot_Mnt2"); } }
		private long? _Ac_Tot_Qty; public long? Ac_Tot_Qty { get { return _Ac_Tot_Qty; } set { Set(ref _Ac_Tot_Qty, value, "Ac_Tot_Qty"); } }
		private decimal? _Ac_Mnt; public decimal? Ac_Mnt { get { return _Ac_Mnt; } set { Set(ref _Ac_Mnt, value, "Ac_Mnt"); } }
		private string _Notes; public string Notes { get { return _Notes; } set { Set(ref _Notes, value, "Notes"); } }
		private int? _Idgl_Inv; public int? Idgl_Inv { get { return _Idgl_Inv; } set { Set(ref _Idgl_Inv, value, "Idgl_Inv"); } }
		private int? _Idgl_Adj; public int? Idgl_Adj { get { return _Idgl_Adj; } set { Set(ref _Idgl_Adj, value, "Idgl_Adj"); } }
		private int? _Dim1; public int? Dim1 { get { return _Dim1; } set { Set(ref _Dim1, value, "Dim1"); } }
		private int? _Dim2; public int? Dim2 { get { return _Dim2; } set { Set(ref _Dim2, value, "Dim2"); } }
		private int? _Dim3; public int? Dim3 { get { return _Dim3; } set { Set(ref _Dim3, value, "Dim3"); } }
		private decimal? _Weight; public decimal? Weight { get { return _Weight; } set { Set(ref _Weight, value, "Weight"); } }
		private decimal? _Ac_Mnt2; public decimal? Ac_Mnt2 { get { return _Ac_Mnt2; } set { Set(ref _Ac_Mnt2, value, "Ac_Mnt2"); } }
		private decimal? _Ac_Lst_Cost; public decimal? Ac_Lst_Cost { get { return _Ac_Lst_Cost; } set { Set(ref _Ac_Lst_Cost, value, "Ac_Lst_Cost"); } }
		private int? _Idgl_Rev; public int? Idgl_Rev { get { return _Idgl_Rev; } set { Set(ref _Idgl_Rev, value, "Idgl_Rev"); } }
		private bool? _Is_Service; public bool? Is_Service { get { return _Is_Service; } set { Set(ref _Is_Service, value, "Is_Service"); } }
		private decimal? _Pourc_Agent; public decimal? Pourc_Agent { get { return _Pourc_Agent; } set { Set(ref _Pourc_Agent, value, "Pourc_Agent"); } }
		private int? _Def_Warh; public int? Def_Warh { get { return _Def_Warh; } set { Set(ref _Def_Warh, value, "Def_Warh"); } }
		private string _Unit; public string Unit { get { return _Unit; } set { Set(ref _Unit, value, "Unit"); } }
		private string _Pms1; public string Pms1 { get { return _Pms1; } set { Set(ref _Pms1, value, "Pms1"); } }
		private string _Pms2; public string Pms2 { get { return _Pms2; } set { Set(ref _Pms2, value, "Pms2"); } }
		private string _Pms3; public string Pms3 { get { return _Pms3; } set { Set(ref _Pms3, value, "Pms3"); } }
		private string _Pms4; public string Pms4 { get { return _Pms4; } set { Set(ref _Pms4, value, "Pms4"); } }
		private string _Pms5; public string Pms5 { get { return _Pms5; } set { Set(ref _Pms5, value, "Pms5"); } }
		private string _Pms6; public string Pms6 { get { return _Pms6; } set { Set(ref _Pms6, value, "Pms6"); } }
		private string _Pms7; public string Pms7 { get { return _Pms7; } set { Set(ref _Pms7, value, "Pms7"); } }
		private string _Pms8; public string Pms8 { get { return _Pms8; } set { Set(ref _Pms8, value, "Pms8"); } }
		private string _Longueur; public string Longueur { get { return _Longueur; } set { Set(ref _Longueur, value, "Longueur"); } }
		private string _Largeur; public string Largeur { get { return _Largeur; } set { Set(ref _Largeur, value, "Largeur"); } }
		private string _Hauteur; public string Hauteur { get { return _Hauteur; } set { Set(ref _Hauteur, value, "Hauteur"); } }
		private string _Unite; public string Unite { get { return _Unite; } set { Set(ref _Unite, value, "Unite"); } }
		private string _Dureemax; public string Dureemax { get { return _Dureemax; } set { Set(ref _Dureemax, value, "Dureemax"); } }
		private long? _Qty_Min; public long? Qty_Min { get { return _Qty_Min; } set { Set(ref _Qty_Min, value, "Qty_Min"); } }
		private string _Location; public string Location { get { return _Location; } set { Set(ref _Location, value, "Location"); } }
		private int? _Idgl_Cost; public int? Idgl_Cost { get { return _Idgl_Cost; } set { Set(ref _Idgl_Cost, value, "Idgl_Cost"); } }
		private bool? _Consign; public bool? Consign { get { return _Consign; } set { Set(ref _Consign, value, "Consign"); } }
		private bool? _Recommande_Auto; public bool? Recommande_Auto { get { return _Recommande_Auto; } set { Set(ref _Recommande_Auto, value, "Recommande_Auto"); } }
		private long? _Qty_Max; public long? Qty_Max { get { return _Qty_Max; } set { Set(ref _Qty_Max, value, "Qty_Max"); } }
		private string _Cr_By; public string Cr_By { get { return _Cr_By; } set { Set(ref _Cr_By, value, "Cr_By"); } }
		private DateTime? _Cr_Dtime; public DateTime? Cr_Dtime { get { return _Cr_Dtime; } set { Set(ref _Cr_Dtime, value, "Cr_Dtime"); } }
		private string _Mod_By; public string Mod_By { get { return _Mod_By; } set { Set(ref _Mod_By, value, "Mod_By"); } }
		private DateTime? _Mod_Dtime; public DateTime? Mod_Dtime { get { return _Mod_Dtime; } set { Set(ref _Mod_Dtime, value, "Mod_Dtime"); } }
		private string _Recomm_Note; public string Recomm_Note { get { return _Recomm_Note; } set { Set(ref _Recomm_Note, value, "Recomm_Note"); } }
		private decimal? _N_Longueur; public decimal? N_Longueur { get { return _N_Longueur; } set { Set(ref _N_Longueur, value, "N_Longueur"); } }
		private decimal? _N_Largeur; public decimal? N_Largeur { get { return _N_Largeur; } set { Set(ref _N_Largeur, value, "N_Largeur"); } }
		private decimal? _N_Hauteur; public decimal? N_Hauteur { get { return _N_Hauteur; } set { Set(ref _N_Hauteur, value, "N_Hauteur"); } }
		private decimal? _Sh_Size_Longueur; public decimal? Sh_Size_Longueur { get { return _Sh_Size_Longueur; } set { Set(ref _Sh_Size_Longueur, value, "Sh_Size_Longueur"); } }
		private decimal? _Sh_Size_Largeur; public decimal? Sh_Size_Largeur { get { return _Sh_Size_Largeur; } set { Set(ref _Sh_Size_Largeur, value, "Sh_Size_Largeur"); } }
		private decimal? _Calc_Total; public decimal? Calc_Total { get { return _Calc_Total; } set { Set(ref _Calc_Total, value, "Calc_Total"); } }
		private decimal? _Gap_Top; public decimal? Gap_Top { get { return _Gap_Top; } set { Set(ref _Gap_Top, value, "Gap_Top"); } }
		private decimal? _Gap_Bot; public decimal? Gap_Bot { get { return _Gap_Bot; } set { Set(ref _Gap_Bot, value, "Gap_Bot"); } }
		private decimal? _Overlap_Top; public decimal? Overlap_Top { get { return _Overlap_Top; } set { Set(ref _Overlap_Top, value, "Overlap_Top"); } }
		private decimal? _Overlap_Bot; public decimal? Overlap_Bot { get { return _Overlap_Bot; } set { Set(ref _Overlap_Bot, value, "Overlap_Bot"); } }
		private string _Fig; public string Fig { get { return _Fig; } set { Set(ref _Fig, value, "Fig"); } }
		private string _Code_Pal; public string Code_Pal { get { return _Code_Pal; } set { Set(ref _Code_Pal, value, "Code_Pal"); } }
		private long? _Cur_Stock; public long? Cur_Stock { get { return _Cur_Stock; } set { Set(ref _Cur_Stock, value, "Cur_Stock"); } }
		private long? _Cur_Liv_Not_Fact; public long? Cur_Liv_Not_Fact { get { return _Cur_Liv_Not_Fact; } set { Set(ref _Cur_Liv_Not_Fact, value, "Cur_Liv_Not_Fact"); } }
		private bool? _From_Kit; public bool? From_Kit { get { return _From_Kit; } set { Set(ref _From_Kit, value, "From_Kit"); } }
		private bool? _Is_Kit; public bool? Is_Kit { get { return _Is_Kit; } set { Set(ref _Is_Kit, value, "Is_Kit"); } }
		private DateTime? _Recom_Date_Report; public DateTime? Recom_Date_Report { get { return _Recom_Date_Report; } set { Set(ref _Recom_Date_Report, value, "Recom_Date_Report"); } }
		private int? _Idmaitre; public int? Idmaitre { get { return _Idmaitre; } set { Set(ref _Idmaitre, value, "Idmaitre"); } }
		private string _Maitre_Notes; public string Maitre_Notes { get { return _Maitre_Notes; } set { Set(ref _Maitre_Notes, value, "Maitre_Notes"); } }
		private bool? _Liquidation; public bool? Liquidation { get { return _Liquidation; } set { Set(ref _Liquidation, value, "Liquidation"); } }
		private string _Liquid_Note; public string Liquid_Note { get { return _Liquid_Note; } set { Set(ref _Liquid_Note, value, "Liquid_Note"); } }
		private int? _Poids_Lb_Ballot; public int? Poids_Lb_Ballot { get { return _Poids_Lb_Ballot; } set { Set(ref _Poids_Lb_Ballot, value, "Poids_Lb_Ballot"); } }
		private decimal? _Longueur_Ballot; public decimal? Longueur_Ballot { get { return _Longueur_Ballot; } set { Set(ref _Longueur_Ballot, value, "Longueur_Ballot"); } }
		private decimal? _Largeur_Ballot; public decimal? Largeur_Ballot { get { return _Largeur_Ballot; } set { Set(ref _Largeur_Ballot, value, "Largeur_Ballot"); } }
		private decimal? _Hauteur_Ballot; public decimal? Hauteur_Ballot { get { return _Hauteur_Ballot; } set { Set(ref _Hauteur_Ballot, value, "Hauteur_Ballot"); } }
		private bool? _Web_Permanent; public bool? Web_Permanent { get { return _Web_Permanent; } set { Set(ref _Web_Permanent, value, "Web_Permanent"); } }
		private decimal? _Web_Prix; public decimal? Web_Prix { get { return _Web_Prix; } set { Set(ref _Web_Prix, value, "Web_Prix"); } }
		private decimal? _Web_Prixpal; public decimal? Web_Prixpal { get { return _Web_Prixpal; } set { Set(ref _Web_Prixpal, value, "Web_Prixpal"); } }
		private string _Web_Note; public string Web_Note { get { return _Web_Note; } set { Set(ref _Web_Note, value, "Web_Note"); } }
		private bool? _Audessus; public bool? Audessus { get { return _Audessus; } set { Set(ref _Audessus, value, "Audessus"); } }
		private int? _Hino; public int? Hino { get { return _Hino; } set { Set(ref _Hino, value, "Hino"); } }
		private int? _T206no; public int? T206no { get { return _T206no; } set { Set(ref _T206no, value, "T206no"); } }
		private int? _T503pc; public int? T503pc { get { return _T503pc; } set { Set(ref _T503pc, value, "T503pc"); } }
		private int? _Pas_Palet; public int? Pas_Palet { get { return _Pas_Palet; } set { Set(ref _Pas_Palet, value, "Pas_Palet"); } }
		private bool? _Nolot; public bool? Nolot { get { return _Nolot; } set { Set(ref _Nolot, value, "Nolot"); } }
		private decimal? _Dern_Ven; public decimal? Dern_Ven { get { return _Dern_Ven; } set { Set(ref _Dern_Ven, value, "Dern_Ven"); } }
		private long? _Qte_Fab_Kit; public long? Qte_Fab_Kit { get { return _Qte_Fab_Kit; } set { Set(ref _Qte_Fab_Kit, value, "Qte_Fab_Kit"); } }
		private string _Last_Cost_Unit; public string Last_Cost_Unit { get { return _Last_Cost_Unit; } set { Set(ref _Last_Cost_Unit, value, "Last_Cost_Unit"); } }
		private int? _Vend; public int? Vend { get { return _Vend; } set { Set(ref _Vend, value, "Vend"); } }
		private int? _Achat; public int? Achat { get { return _Achat; } set { Set(ref _Achat, value, "Achat"); } }
		private DateTime? _Datmax; public DateTime? Datmax { get { return _Datmax; } set { Set(ref _Datmax, value, "Datmax"); } }
		private bool? _Dim_Est; public bool? Dim_Est { get { return _Dim_Est; } set { Set(ref _Dim_Est, value, "Dim_Est"); } }
		private decimal? _Pour_En1; public decimal? Pour_En1 { get { return _Pour_En1; } set { Set(ref _Pour_En1, value, "Pour_En1"); } }
		private decimal? _Pour_En2; public decimal? Pour_En2 { get { return _Pour_En2; } set { Set(ref _Pour_En2, value, "Pour_En2"); } }
		private decimal? _Pour_En3; public decimal? Pour_En3 { get { return _Pour_En3; } set { Set(ref _Pour_En3, value, "Pour_En3"); } }
		private decimal? _Pour_En4; public decimal? Pour_En4 { get { return _Pour_En4; } set { Set(ref _Pour_En4, value, "Pour_En4"); } }
		private decimal? _Pour_En5; public decimal? Pour_En5 { get { return _Pour_En5; } set { Set(ref _Pour_En5, value, "Pour_En5"); } }
		private decimal? _Pour_En6; public decimal? Pour_En6 { get { return _Pour_En6; } set { Set(ref _Pour_En6, value, "Pour_En6"); } }
		private decimal? _Pour_En7; public decimal? Pour_En7 { get { return _Pour_En7; } set { Set(ref _Pour_En7, value, "Pour_En7"); } }
		private decimal? _Pour_En8; public decimal? Pour_En8 { get { return _Pour_En8; } set { Set(ref _Pour_En8, value, "Pour_En8"); } }
		private string _Pms_Vri1; public string Pms_Vri1 { get { return _Pms_Vri1; } set { Set(ref _Pms_Vri1, value, "Pms_Vri1"); } }
		private string _Pms_Vri2; public string Pms_Vri2 { get { return _Pms_Vri2; } set { Set(ref _Pms_Vri2, value, "Pms_Vri2"); } }
		private string _Pms_Vri3; public string Pms_Vri3 { get { return _Pms_Vri3; } set { Set(ref _Pms_Vri3, value, "Pms_Vri3"); } }
		private string _Pms_Vri4; public string Pms_Vri4 { get { return _Pms_Vri4; } set { Set(ref _Pms_Vri4, value, "Pms_Vri4"); } }
		private string _Pms_Vri5; public string Pms_Vri5 { get { return _Pms_Vri5; } set { Set(ref _Pms_Vri5, value, "Pms_Vri5"); } }
		private string _Pms_Vri6; public string Pms_Vri6 { get { return _Pms_Vri6; } set { Set(ref _Pms_Vri6, value, "Pms_Vri6"); } }
		private string _Pms_Vri7; public string Pms_Vri7 { get { return _Pms_Vri7; } set { Set(ref _Pms_Vri7, value, "Pms_Vri7"); } }
		private string _Pms_Vri8; public string Pms_Vri8 { get { return _Pms_Vri8; } set { Set(ref _Pms_Vri8, value, "Pms_Vri8"); } }
		private int? _Qteboi; public int? Qteboi { get { return _Qteboi; } set { Set(ref _Qteboi, value, "Qteboi"); } }
		private int? _Qteboimas; public int? Qteboimas { get { return _Qteboimas; } set { Set(ref _Qteboimas, value, "Qteboimas"); } }
		private bool? _Papier; public bool? Papier { get { return _Papier; } set { Set(ref _Papier, value, "Papier"); } }
		private string _Nofsc; public string Nofsc { get { return _Nofsc; } set { Set(ref _Nofsc, value, "Nofsc"); } }
		private int? _Idfsc; public int? Idfsc { get { return _Idfsc; } set { Set(ref _Idfsc, value, "Idfsc"); } }
		private int? _Qtepaquet; public int? Qtepaquet { get { return _Qtepaquet; } set { Set(ref _Qtepaquet, value, "Qtepaquet"); } }
		private bool? _Web_Contrat; public bool? Web_Contrat { get { return _Web_Contrat; } set { Set(ref _Web_Contrat, value, "Web_Contrat"); } }
		private decimal? _Web_Qtepal; public decimal? Web_Qtepal { get { return _Web_Qtepal; } set { Set(ref _Web_Qtepal, value, "Web_Qtepal"); } }

	}
}