using System;

namespace vivael
{
	public class data_estima : DataSource
	{
		public data_estima() { Table_name = i.name = "estima"; i.primary_1 = "ident"; i.primary_2 = null; i.primary_3 = null; isFoxpro = true; }

		private int _Ident; public int Ident { get { return _Ident; } set { Set(ref _Ident, value, "Ident"); } }
		private int? _Idprod; public int? Idprod { get { return _Idprod; } set { Set(ref _Idprod, value, "Idprod"); } }
		private int? _Idmat; public int? Idmat { get { return _Idmat; } set { Set(ref _Idmat, value, "Idmat"); } }
		private int? _Idmach1; public int? Idmach1 { get { return _Idmach1; } set { Set(ref _Idmach1, value, "Idmach1"); } }
		private int? _Idmach2; public int? Idmach2 { get { return _Idmach2; } set { Set(ref _Idmach2, value, "Idmach2"); } }
		private int? _Idmach3; public int? Idmach3 { get { return _Idmach3; } set { Set(ref _Idmach3, value, "Idmach3"); } }
		private int? _Idmach4; public int? Idmach4 { get { return _Idmach4; } set { Set(ref _Idmach4, value, "Idmach4"); } }
		private int? _Idmach5; public int? Idmach5 { get { return _Idmach5; } set { Set(ref _Idmach5, value, "Idmach5"); } }
		private int? _Idmach6; public int? Idmach6 { get { return _Idmach6; } set { Set(ref _Idmach6, value, "Idmach6"); } }
		private int? _Idmach7; public int? Idmach7 { get { return _Idmach7; } set { Set(ref _Idmach7, value, "Idmach7"); } }
		private short? _Perte1; public short? Perte1 { get { return _Perte1; } set { Set(ref _Perte1, value, "Perte1"); } }
		private short? _Perte2; public short? Perte2 { get { return _Perte2; } set { Set(ref _Perte2, value, "Perte2"); } }
		private short? _Perte3; public short? Perte3 { get { return _Perte3; } set { Set(ref _Perte3, value, "Perte3"); } }
		private short? _Perte4; public short? Perte4 { get { return _Perte4; } set { Set(ref _Perte4, value, "Perte4"); } }
		private short? _Perte5; public short? Perte5 { get { return _Perte5; } set { Set(ref _Perte5, value, "Perte5"); } }
		private short? _Perte6; public short? Perte6 { get { return _Perte6; } set { Set(ref _Perte6, value, "Perte6"); } }
		private short? _Perte7; public short? Perte7 { get { return _Perte7; } set { Set(ref _Perte7, value, "Perte7"); } }
		private short? _Pertem1; public short? Pertem1 { get { return _Pertem1; } set { Set(ref _Pertem1, value, "Pertem1"); } }
		private short? _Pertem2; public short? Pertem2 { get { return _Pertem2; } set { Set(ref _Pertem2, value, "Pertem2"); } }
		private short? _Pertem3; public short? Pertem3 { get { return _Pertem3; } set { Set(ref _Pertem3, value, "Pertem3"); } }
		private short? _Pertem4; public short? Pertem4 { get { return _Pertem4; } set { Set(ref _Pertem4, value, "Pertem4"); } }
		private short? _Pertem5; public short? Pertem5 { get { return _Pertem5; } set { Set(ref _Pertem5, value, "Pertem5"); } }
		private short? _Pertem6; public short? Pertem6 { get { return _Pertem6; } set { Set(ref _Pertem6, value, "Pertem6"); } }
		private short? _Pertem7; public short? Pertem7 { get { return _Pertem7; } set { Set(ref _Pertem7, value, "Pertem7"); } }
		private int? _Nbenvh1; public int? Nbenvh1 { get { return _Nbenvh1; } set { Set(ref _Nbenvh1, value, "Nbenvh1"); } }
		private int? _Nbenvh2; public int? Nbenvh2 { get { return _Nbenvh2; } set { Set(ref _Nbenvh2, value, "Nbenvh2"); } }
		private int? _Nbenvh3; public int? Nbenvh3 { get { return _Nbenvh3; } set { Set(ref _Nbenvh3, value, "Nbenvh3"); } }
		private int? _Nbenvh4; public int? Nbenvh4 { get { return _Nbenvh4; } set { Set(ref _Nbenvh4, value, "Nbenvh4"); } }
		private int? _Nbenvh5; public int? Nbenvh5 { get { return _Nbenvh5; } set { Set(ref _Nbenvh5, value, "Nbenvh5"); } }
		private int? _Nbenvh6; public int? Nbenvh6 { get { return _Nbenvh6; } set { Set(ref _Nbenvh6, value, "Nbenvh6"); } }
		private int? _Nbenvh7; public int? Nbenvh7 { get { return _Nbenvh7; } set { Set(ref _Nbenvh7, value, "Nbenvh7"); } }
		private int? _Nbenvhm1; public int? Nbenvhm1 { get { return _Nbenvhm1; } set { Set(ref _Nbenvhm1, value, "Nbenvhm1"); } }
		private int? _Nbenvhm2; public int? Nbenvhm2 { get { return _Nbenvhm2; } set { Set(ref _Nbenvhm2, value, "Nbenvhm2"); } }
		private int? _Nbenvhm3; public int? Nbenvhm3 { get { return _Nbenvhm3; } set { Set(ref _Nbenvhm3, value, "Nbenvhm3"); } }
		private int? _Nbenvhm4; public int? Nbenvhm4 { get { return _Nbenvhm4; } set { Set(ref _Nbenvhm4, value, "Nbenvhm4"); } }
		private int? _Nbenvhm5; public int? Nbenvhm5 { get { return _Nbenvhm5; } set { Set(ref _Nbenvhm5, value, "Nbenvhm5"); } }
		private int? _Nbenvhm6; public int? Nbenvhm6 { get { return _Nbenvhm6; } set { Set(ref _Nbenvhm6, value, "Nbenvhm6"); } }
		private int? _Nbenvhm7; public int? Nbenvhm7 { get { return _Nbenvhm7; } set { Set(ref _Nbenvhm7, value, "Nbenvhm7"); } }
		private decimal? _Setup1; public decimal? Setup1 { get { return _Setup1; } set { Set(ref _Setup1, value, "Setup1"); } }
		private decimal? _Setup2; public decimal? Setup2 { get { return _Setup2; } set { Set(ref _Setup2, value, "Setup2"); } }
		private decimal? _Setup3; public decimal? Setup3 { get { return _Setup3; } set { Set(ref _Setup3, value, "Setup3"); } }
		private decimal? _Setup4; public decimal? Setup4 { get { return _Setup4; } set { Set(ref _Setup4, value, "Setup4"); } }
		private decimal? _Setup5; public decimal? Setup5 { get { return _Setup5; } set { Set(ref _Setup5, value, "Setup5"); } }
		private decimal? _Setup6; public decimal? Setup6 { get { return _Setup6; } set { Set(ref _Setup6, value, "Setup6"); } }
		private decimal? _Setup7; public decimal? Setup7 { get { return _Setup7; } set { Set(ref _Setup7, value, "Setup7"); } }
		private decimal? _Setupm1; public decimal? Setupm1 { get { return _Setupm1; } set { Set(ref _Setupm1, value, "Setupm1"); } }
		private decimal? _Setupm2; public decimal? Setupm2 { get { return _Setupm2; } set { Set(ref _Setupm2, value, "Setupm2"); } }
		private decimal? _Setupm3; public decimal? Setupm3 { get { return _Setupm3; } set { Set(ref _Setupm3, value, "Setupm3"); } }
		private decimal? _Setupm4; public decimal? Setupm4 { get { return _Setupm4; } set { Set(ref _Setupm4, value, "Setupm4"); } }
		private decimal? _Setupm5; public decimal? Setupm5 { get { return _Setupm5; } set { Set(ref _Setupm5, value, "Setupm5"); } }
		private decimal? _Setupm6; public decimal? Setupm6 { get { return _Setupm6; } set { Set(ref _Setupm6, value, "Setupm6"); } }
		private decimal? _Setupm7; public decimal? Setupm7 { get { return _Setupm7; } set { Set(ref _Setupm7, value, "Setupm7"); } }
		private int? _Qtepaq; public int? Qtepaq { get { return _Qtepaq; } set { Set(ref _Qtepaq, value, "Qtepaq"); } }
		private int? _Qteboi; public int? Qteboi { get { return _Qteboi; } set { Set(ref _Qteboi, value, "Qteboi"); } }
		private int? _Qtemas; public int? Qtemas { get { return _Qtemas; } set { Set(ref _Qtemas, value, "Qtemas"); } }
		private int? _Qtep14; public int? Qtep14 { get { return _Qtep14; } set { Set(ref _Qtep14, value, "Qtep14"); } }
		private int? _Qtep12; public int? Qtep12 { get { return _Qtep12; } set { Set(ref _Qtep12, value, "Qtep12"); } }
		private int? _Qtepal; public int? Qtepal { get { return _Qtepal; } set { Set(ref _Qtepal, value, "Qtepal"); } }
		private int? _Qte2pal; public int? Qte2pal { get { return _Qte2pal; } set { Set(ref _Qte2pal, value, "Qte2pal"); } }
		private int? _Qte5pal; public int? Qte5pal { get { return _Qte5pal; } set { Set(ref _Qte5pal, value, "Qte5pal"); } }
		private int? _Qtevl; public int? Qtevl { get { return _Qtevl; } set { Set(ref _Qtevl, value, "Qtevl"); } }
		private int? _Qtemas2; public int? Qtemas2 { get { return _Qtemas2; } set { Set(ref _Qtemas2, value, "Qtemas2"); } }
		private int? _Qtep18; public int? Qtep18 { get { return _Qtep18; } set { Set(ref _Qtep18, value, "Qtep18"); } }
		private int? _Qteaut; public int? Qteaut { get { return _Qteaut; } set { Set(ref _Qteaut, value, "Qteaut"); } }
		private decimal? _Prixtpaq; public decimal? Prixtpaq { get { return _Prixtpaq; } set { Set(ref _Prixtpaq, value, "Prixtpaq"); } }
		private decimal? _Prixtboi; public decimal? Prixtboi { get { return _Prixtboi; } set { Set(ref _Prixtboi, value, "Prixtboi"); } }
		private decimal? _Prixtmas; public decimal? Prixtmas { get { return _Prixtmas; } set { Set(ref _Prixtmas, value, "Prixtmas"); } }
		private decimal? _Prixtp14; public decimal? Prixtp14 { get { return _Prixtp14; } set { Set(ref _Prixtp14, value, "Prixtp14"); } }
		private decimal? _Prixtp12; public decimal? Prixtp12 { get { return _Prixtp12; } set { Set(ref _Prixtp12, value, "Prixtp12"); } }
		private decimal? _Prixtpal; public decimal? Prixtpal { get { return _Prixtpal; } set { Set(ref _Prixtpal, value, "Prixtpal"); } }
		private decimal? _Ptrixt2pal; public decimal? Ptrixt2pal { get { return _Ptrixt2pal; } set { Set(ref _Ptrixt2pal, value, "Ptrixt2pal"); } }
		private decimal? _Prixt5pal; public decimal? Prixt5pal { get { return _Prixt5pal; } set { Set(ref _Prixt5pal, value, "Prixt5pal"); } }
		private decimal? _Prixtvl; public decimal? Prixtvl { get { return _Prixtvl; } set { Set(ref _Prixtvl, value, "Prixtvl"); } }
		private decimal? _Prixtmas2; public decimal? Prixtmas2 { get { return _Prixtmas2; } set { Set(ref _Prixtmas2, value, "Prixtmas2"); } }
		private decimal? _Prixtp18; public decimal? Prixtp18 { get { return _Prixtp18; } set { Set(ref _Prixtp18, value, "Prixtp18"); } }
		private decimal? _Prixtaut; public decimal? Prixtaut { get { return _Prixtaut; } set { Set(ref _Prixtaut, value, "Prixtaut"); } }
		private decimal? _Prixpaq; public decimal? Prixpaq { get { return _Prixpaq; } set { Set(ref _Prixpaq, value, "Prixpaq"); } }
		private decimal? _Prixboi; public decimal? Prixboi { get { return _Prixboi; } set { Set(ref _Prixboi, value, "Prixboi"); } }
		private decimal? _Prixmas; public decimal? Prixmas { get { return _Prixmas; } set { Set(ref _Prixmas, value, "Prixmas"); } }
		private decimal? _Prixp14; public decimal? Prixp14 { get { return _Prixp14; } set { Set(ref _Prixp14, value, "Prixp14"); } }
		private decimal? _Prixp12; public decimal? Prixp12 { get { return _Prixp12; } set { Set(ref _Prixp12, value, "Prixp12"); } }
		private decimal? _Prixpal; public decimal? Prixpal { get { return _Prixpal; } set { Set(ref _Prixpal, value, "Prixpal"); } }
		private decimal? _Prix2pal; public decimal? Prix2pal { get { return _Prix2pal; } set { Set(ref _Prix2pal, value, "Prix2pal"); } }
		private decimal? _Prix5pal; public decimal? Prix5pal { get { return _Prix5pal; } set { Set(ref _Prix5pal, value, "Prix5pal"); } }
		private decimal? _Prixvl; public decimal? Prixvl { get { return _Prixvl; } set { Set(ref _Prixvl, value, "Prixvl"); } }
		private decimal? _Prixmas2; public decimal? Prixmas2 { get { return _Prixmas2; } set { Set(ref _Prixmas2, value, "Prixmas2"); } }
		private decimal? _Prixp18; public decimal? Prixp18 { get { return _Prixp18; } set { Set(ref _Prixp18, value, "Prixp18"); } }
		private decimal? _Prixaut; public decimal? Prixaut { get { return _Prixaut; } set { Set(ref _Prixaut, value, "Prixaut"); } }
		private decimal? _Prixpmpaq; public decimal? Prixpmpaq { get { return _Prixpmpaq; } set { Set(ref _Prixpmpaq, value, "Prixpmpaq"); } }
		private decimal? _Prixpmboi; public decimal? Prixpmboi { get { return _Prixpmboi; } set { Set(ref _Prixpmboi, value, "Prixpmboi"); } }
		private decimal? _Prixpmmas; public decimal? Prixpmmas { get { return _Prixpmmas; } set { Set(ref _Prixpmmas, value, "Prixpmmas"); } }
		private decimal? _Prixpmp14; public decimal? Prixpmp14 { get { return _Prixpmp14; } set { Set(ref _Prixpmp14, value, "Prixpmp14"); } }
		private decimal? _Prixpmp12; public decimal? Prixpmp12 { get { return _Prixpmp12; } set { Set(ref _Prixpmp12, value, "Prixpmp12"); } }
		private decimal? _Prixpmpal; public decimal? Prixpmpal { get { return _Prixpmpal; } set { Set(ref _Prixpmpal, value, "Prixpmpal"); } }
		private decimal? _Prixpm2pal; public decimal? Prixpm2pal { get { return _Prixpm2pal; } set { Set(ref _Prixpm2pal, value, "Prixpm2pal"); } }
		private decimal? _Prixpm5pal; public decimal? Prixpm5pal { get { return _Prixpm5pal; } set { Set(ref _Prixpm5pal, value, "Prixpm5pal"); } }
		private decimal? _Prixpmvl; public decimal? Prixpmvl { get { return _Prixpmvl; } set { Set(ref _Prixpmvl, value, "Prixpmvl"); } }
		private decimal? _Prixpmmas2; public decimal? Prixpmmas2 { get { return _Prixpmmas2; } set { Set(ref _Prixpmmas2, value, "Prixpmmas2"); } }
		private decimal? _Prixpmp18; public decimal? Prixpmp18 { get { return _Prixpmp18; } set { Set(ref _Prixpmp18, value, "Prixpmp18"); } }
		private decimal? _Prixpmaut; public decimal? Prixpmaut { get { return _Prixpmaut; } set { Set(ref _Prixpmaut, value, "Prixpmaut"); } }
		private string _Statut; public string Statut { get { return _Statut; } set { Set(ref _Statut, value, "Statut"); } }
		private string _Notes; public string Notes { get { return _Notes; } set { Set(ref _Notes, value, "Notes"); } }
		private DateTime? _Dte; public DateTime? Dte { get { return _Dte; } set { Set(ref _Dte, value, "Dte"); } }
		private DateTime? _Datedem; public DateTime? Datedem { get { return _Datedem; } set { Set(ref _Datedem, value, "Datedem"); } }
		private DateTime? _Cr_Dte; public DateTime? Cr_Dte { get { return _Cr_Dte; } set { Set(ref _Cr_Dte, value, "Cr_Dte"); } }
		private string _Cr_By; public string Cr_By { get { return _Cr_By; } set { Set(ref _Cr_By, value, "Cr_By"); } }
		private DateTime? _Mod_Dte; public DateTime? Mod_Dte { get { return _Mod_Dte; } set { Set(ref _Mod_Dte, value, "Mod_Dte"); } }
		private string _Mod_By; public string Mod_By { get { return _Mod_By; } set { Set(ref _Mod_By, value, "Mod_By"); } }
		private decimal? _Nbrplaq; public decimal? Nbrplaq { get { return _Nbrplaq; } set { Set(ref _Nbrplaq, value, "Nbrplaq"); } }
		private decimal? _Nbrcoul; public decimal? Nbrcoul { get { return _Nbrcoul; } set { Set(ref _Nbrcoul, value, "Nbrcoul"); } }
		private decimal? _Nbrmat; public decimal? Nbrmat { get { return _Nbrmat; } set { Set(ref _Nbrmat, value, "Nbrmat"); } }
		private decimal? _Coutplaq; public decimal? Coutplaq { get { return _Coutplaq; } set { Set(ref _Coutplaq, value, "Coutplaq"); } }
		private decimal? _Coutcou; public decimal? Coutcou { get { return _Coutcou; } set { Set(ref _Coutcou, value, "Coutcou"); } }
		private decimal? _Coutmat; public decimal? Coutmat { get { return _Coutmat; } set { Set(ref _Coutmat, value, "Coutmat"); } }

	}
}