using System;

namespace vivael
{
	public class data_apsupp : DataSource
	{
		public data_apsupp() { Table_name = i.name = "apsupp"; i.primary_1 = "ident"; i.primary_2 = null; i.primary_3 = null; isFoxpro = true; }

		private int _Ident; public int Ident { get { return _Ident; } set { Set(ref _Ident, value, "Ident"); } }
		private string _Code; public string Code { get { return _Code; } set { Set(ref _Code, value, "Code"); } }
		private string _Name; public string Name { get { return _Name; } set { Set(ref _Name, value, "Name"); } }
		private string _Offname; public string Offname { get { return _Offname; } set { Set(ref _Offname, value, "Offname"); } }
		private string _Status; public string Status { get { return _Status; } set { Set(ref _Status, value, "Status"); } }
		private string _Accnt_No; public string Accnt_No { get { return _Accnt_No; } set { Set(ref _Accnt_No, value, "Accnt_No"); } }
		private string _Language; public string Language { get { return _Language; } set { Set(ref _Language, value, "Language"); } }
		private string _Addr1; public string Addr1 { get { return _Addr1; } set { Set(ref _Addr1, value, "Addr1"); } }
		private string _Addr2; public string Addr2 { get { return _Addr2; } set { Set(ref _Addr2, value, "Addr2"); } }
		private string _City; public string City { get { return _City; } set { Set(ref _City, value, "City"); } }
		private string _State; public string State { get { return _State; } set { Set(ref _State, value, "State"); } }
		private string _Zip; public string Zip { get { return _Zip; } set { Set(ref _Zip, value, "Zip"); } }
		private string _Country; public string Country { get { return _Country; } set { Set(ref _Country, value, "Country"); } }
		private string _Del_Addr1; public string Del_Addr1 { get { return _Del_Addr1; } set { Set(ref _Del_Addr1, value, "Del_Addr1"); } }
		private string _Del_Addr2; public string Del_Addr2 { get { return _Del_Addr2; } set { Set(ref _Del_Addr2, value, "Del_Addr2"); } }
		private string _Del_City; public string Del_City { get { return _Del_City; } set { Set(ref _Del_City, value, "Del_City"); } }
		private string _Del_State; public string Del_State { get { return _Del_State; } set { Set(ref _Del_State, value, "Del_State"); } }
		private string _Del_Zip; public string Del_Zip { get { return _Del_Zip; } set { Set(ref _Del_Zip, value, "Del_Zip"); } }
		private string _Del_Country; public string Del_Country { get { return _Del_Country; } set { Set(ref _Del_Country, value, "Del_Country"); } }
		private string _Pay_Name; public string Pay_Name { get { return _Pay_Name; } set { Set(ref _Pay_Name, value, "Pay_Name"); } }
		private string _Pay_Addr1; public string Pay_Addr1 { get { return _Pay_Addr1; } set { Set(ref _Pay_Addr1, value, "Pay_Addr1"); } }
		private string _Pay_Addr2; public string Pay_Addr2 { get { return _Pay_Addr2; } set { Set(ref _Pay_Addr2, value, "Pay_Addr2"); } }
		private string _Pay_City; public string Pay_City { get { return _Pay_City; } set { Set(ref _Pay_City, value, "Pay_City"); } }
		private string _Pay_State; public string Pay_State { get { return _Pay_State; } set { Set(ref _Pay_State, value, "Pay_State"); } }
		private string _Pay_Zip; public string Pay_Zip { get { return _Pay_Zip; } set { Set(ref _Pay_Zip, value, "Pay_Zip"); } }
		private string _Pay_Country; public string Pay_Country { get { return _Pay_Country; } set { Set(ref _Pay_Country, value, "Pay_Country"); } }
		private string _Tel1; public string Tel1 { get { return _Tel1; } set { Set(ref _Tel1, value, "Tel1"); } }
		private string _Tel2; public string Tel2 { get { return _Tel2; } set { Set(ref _Tel2, value, "Tel2"); } }
		private string _Fax; public string Fax { get { return _Fax; } set { Set(ref _Fax, value, "Fax"); } }
		private string _Email; public string Email { get { return _Email; } set { Set(ref _Email, value, "Email"); } }
		private string _Web; public string Web { get { return _Web; } set { Set(ref _Web, value, "Web"); } }
		private string _Cont1_Name; public string Cont1_Name { get { return _Cont1_Name; } set { Set(ref _Cont1_Name, value, "Cont1_Name"); } }
		private string _Cont1_Title; public string Cont1_Title { get { return _Cont1_Title; } set { Set(ref _Cont1_Title, value, "Cont1_Title"); } }
		private string _Cont1_Tel; public string Cont1_Tel { get { return _Cont1_Tel; } set { Set(ref _Cont1_Tel, value, "Cont1_Tel"); } }
		private string _Cont1_Fax; public string Cont1_Fax { get { return _Cont1_Fax; } set { Set(ref _Cont1_Fax, value, "Cont1_Fax"); } }
		private string _Cont1_Email; public string Cont1_Email { get { return _Cont1_Email; } set { Set(ref _Cont1_Email, value, "Cont1_Email"); } }
		private string _Cont2_Name; public string Cont2_Name { get { return _Cont2_Name; } set { Set(ref _Cont2_Name, value, "Cont2_Name"); } }
		private string _Cont2_Title; public string Cont2_Title { get { return _Cont2_Title; } set { Set(ref _Cont2_Title, value, "Cont2_Title"); } }
		private string _Cont2_Tel; public string Cont2_Tel { get { return _Cont2_Tel; } set { Set(ref _Cont2_Tel, value, "Cont2_Tel"); } }
		private string _Cont2_Fax; public string Cont2_Fax { get { return _Cont2_Fax; } set { Set(ref _Cont2_Fax, value, "Cont2_Fax"); } }
		private string _Cont2_Email; public string Cont2_Email { get { return _Cont2_Email; } set { Set(ref _Cont2_Email, value, "Cont2_Email"); } }
		private string _Cont3_Name; public string Cont3_Name { get { return _Cont3_Name; } set { Set(ref _Cont3_Name, value, "Cont3_Name"); } }
		private string _Cont3_Title; public string Cont3_Title { get { return _Cont3_Title; } set { Set(ref _Cont3_Title, value, "Cont3_Title"); } }
		private string _Cont3_Tel; public string Cont3_Tel { get { return _Cont3_Tel; } set { Set(ref _Cont3_Tel, value, "Cont3_Tel"); } }
		private string _Cont3_Fax; public string Cont3_Fax { get { return _Cont3_Fax; } set { Set(ref _Cont3_Fax, value, "Cont3_Fax"); } }
		private string _Cont3_Email; public string Cont3_Email { get { return _Cont3_Email; } set { Set(ref _Cont3_Email, value, "Cont3_Email"); } }
		private string _Notes; public string Notes { get { return _Notes; } set { Set(ref _Notes, value, "Notes"); } }
		private string _Category; public string Category { get { return _Category; } set { Set(ref _Category, value, "Category"); } }
		private string _Region; public string Region { get { return _Region; } set { Set(ref _Region, value, "Region"); } }
		private string _Type; public string Type { get { return _Type; } set { Set(ref _Type, value, "Type"); } }
		private string _Terms; public string Terms { get { return _Terms; } set { Set(ref _Terms, value, "Terms"); } }
		private byte? _Terms_Days; public byte? Terms_Days { get { return _Terms_Days; } set { Set(ref _Terms_Days, value, "Terms_Days"); } }
		private DateTime? _Cr_Date; public DateTime? Cr_Date { get { return _Cr_Date; } set { Set(ref _Cr_Date, value, "Cr_Date"); } }
		private string _Cr_By; public string Cr_By { get { return _Cr_By; } set { Set(ref _Cr_By, value, "Cr_By"); } }
		private DateTime? _Mod_Date; public DateTime? Mod_Date { get { return _Mod_Date; } set { Set(ref _Mod_Date, value, "Mod_Date"); } }
		private string _Mod_By; public string Mod_By { get { return _Mod_By; } set { Set(ref _Mod_By, value, "Mod_By"); } }
		private byte? _Priority; public byte? Priority { get { return _Priority; } set { Set(ref _Priority, value, "Priority"); } }
		private string _Gst_No; public string Gst_No { get { return _Gst_No; } set { Set(ref _Gst_No, value, "Gst_No"); } }
		private string _Pst_No; public string Pst_No { get { return _Pst_No; } set { Set(ref _Pst_No, value, "Pst_No"); } }
		private int? _Idcarrier; public int? Idcarrier { get { return _Idcarrier; } set { Set(ref _Idcarrier, value, "Idcarrier"); } }
		private bool? _Gst_Exempt; public bool? Gst_Exempt { get { return _Gst_Exempt; } set { Set(ref _Gst_Exempt, value, "Gst_Exempt"); } }
		private bool? _Pst_Exempt; public bool? Pst_Exempt { get { return _Pst_Exempt; } set { Set(ref _Pst_Exempt, value, "Pst_Exempt"); } }
		private bool? _Tvh_Ch; public bool? Tvh_Ch { get { return _Tvh_Ch; } set { Set(ref _Tvh_Ch, value, "Tvh_Ch"); } }
		private int? _Idgl_Ap; public int? Idgl_Ap { get { return _Idgl_Ap; } set { Set(ref _Idgl_Ap, value, "Idgl_Ap"); } }
		private string _Curr; public string Curr { get { return _Curr; } set { Set(ref _Curr, value, "Curr"); } }
		private string _Pocode; public string Pocode { get { return _Pocode; } set { Set(ref _Pocode, value, "Pocode"); } }
		private int? _Pono; public int? Pono { get { return _Pono; } set { Set(ref _Pono, value, "Pono"); } }
		private string _Ponotes; public string Ponotes { get { return _Ponotes; } set { Set(ref _Ponotes, value, "Ponotes"); } }
		private bool? _Is_Operation; public bool? Is_Operation { get { return _Is_Operation; } set { Set(ref _Is_Operation, value, "Is_Operation"); } }
		private string _Accpac_Cad; public string Accpac_Cad { get { return _Accpac_Cad; } set { Set(ref _Accpac_Cad, value, "Accpac_Cad"); } }
		private string _Accpac_Usd; public string Accpac_Usd { get { return _Accpac_Usd; } set { Set(ref _Accpac_Usd, value, "Accpac_Usd"); } }
		private bool? _Is_Private; public bool? Is_Private { get { return _Is_Private; } set { Set(ref _Is_Private, value, "Is_Private"); } }
		private string _Ventype; public string Ventype { get { return _Ventype; } set { Set(ref _Ventype, value, "Ventype"); } }
		private short? _Discount_Days; public short? Discount_Days { get { return _Discount_Days; } set { Set(ref _Discount_Days, value, "Discount_Days"); } }
		private decimal? _Discount_Rate; public decimal? Discount_Rate { get { return _Discount_Rate; } set { Set(ref _Discount_Rate, value, "Discount_Rate"); } }
		private string _Add_Info; public string Add_Info { get { return _Add_Info; } set { Set(ref _Add_Info, value, "Add_Info"); } }
		private int? _Idtax; public int? Idtax { get { return _Idtax; } set { Set(ref _Idtax, value, "Idtax"); } }
		private string _Hst_No; public string Hst_No { get { return _Hst_No; } set { Set(ref _Hst_No, value, "Hst_No"); } }
		private bool? _Cf_Appoint; public bool? Cf_Appoint { get { return _Cf_Appoint; } set { Set(ref _Cf_Appoint, value, "Cf_Appoint"); } }
		private string _Cf_Contact; public string Cf_Contact { get { return _Cf_Contact; } set { Set(ref _Cf_Contact, value, "Cf_Contact"); } }
		private string _Cf_Tel; public string Cf_Tel { get { return _Cf_Tel; } set { Set(ref _Cf_Tel, value, "Cf_Tel"); } }
		private bool? _Cf_Certifica; public bool? Cf_Certifica { get { return _Cf_Certifica; } set { Set(ref _Cf_Certifica, value, "Cf_Certifica"); } }
		private int? _Cf_Def_Tr; public int? Cf_Def_Tr { get { return _Cf_Def_Tr; } set { Set(ref _Cf_Def_Tr, value, "Cf_Def_Tr"); } }
		private int? _Cf_Snow_Tr; public int? Cf_Snow_Tr { get { return _Cf_Snow_Tr; } set { Set(ref _Cf_Snow_Tr, value, "Cf_Snow_Tr"); } }
		private string _Cf_Note_Tr; public string Cf_Note_Tr { get { return _Cf_Note_Tr; } set { Set(ref _Cf_Note_Tr, value, "Cf_Note_Tr"); } }
		private bool? _Cf_Lun; public bool? Cf_Lun { get { return _Cf_Lun; } set { Set(ref _Cf_Lun, value, "Cf_Lun"); } }
		private bool? _Cf_Mar; public bool? Cf_Mar { get { return _Cf_Mar; } set { Set(ref _Cf_Mar, value, "Cf_Mar"); } }
		private bool? _Cf_Mer; public bool? Cf_Mer { get { return _Cf_Mer; } set { Set(ref _Cf_Mer, value, "Cf_Mer"); } }
		private bool? _Cf_Jeu; public bool? Cf_Jeu { get { return _Cf_Jeu; } set { Set(ref _Cf_Jeu, value, "Cf_Jeu"); } }
		private bool? _Cf_Ven; public bool? Cf_Ven { get { return _Cf_Ven; } set { Set(ref _Cf_Ven, value, "Cf_Ven"); } }
		private bool? _Cf_Sam; public bool? Cf_Sam { get { return _Cf_Sam; } set { Set(ref _Cf_Sam, value, "Cf_Sam"); } }
		private decimal? _Cf_D1_Lun; public decimal? Cf_D1_Lun { get { return _Cf_D1_Lun; } set { Set(ref _Cf_D1_Lun, value, "Cf_D1_Lun"); } }
		private decimal? _Cf_F1_Lun; public decimal? Cf_F1_Lun { get { return _Cf_F1_Lun; } set { Set(ref _Cf_F1_Lun, value, "Cf_F1_Lun"); } }
		private decimal? _Cf_D1_Mar; public decimal? Cf_D1_Mar { get { return _Cf_D1_Mar; } set { Set(ref _Cf_D1_Mar, value, "Cf_D1_Mar"); } }
		private decimal? _Cf_F1_Mar; public decimal? Cf_F1_Mar { get { return _Cf_F1_Mar; } set { Set(ref _Cf_F1_Mar, value, "Cf_F1_Mar"); } }
		private decimal? _Cf_F1_Mer; public decimal? Cf_F1_Mer { get { return _Cf_F1_Mer; } set { Set(ref _Cf_F1_Mer, value, "Cf_F1_Mer"); } }
		private decimal? _Cf_D1_Mer; public decimal? Cf_D1_Mer { get { return _Cf_D1_Mer; } set { Set(ref _Cf_D1_Mer, value, "Cf_D1_Mer"); } }
		private decimal? _Cf_D1_Jeu; public decimal? Cf_D1_Jeu { get { return _Cf_D1_Jeu; } set { Set(ref _Cf_D1_Jeu, value, "Cf_D1_Jeu"); } }
		private decimal? _Cf_F1_Jeu; public decimal? Cf_F1_Jeu { get { return _Cf_F1_Jeu; } set { Set(ref _Cf_F1_Jeu, value, "Cf_F1_Jeu"); } }
		private decimal? _Cf_D1_Ven; public decimal? Cf_D1_Ven { get { return _Cf_D1_Ven; } set { Set(ref _Cf_D1_Ven, value, "Cf_D1_Ven"); } }
		private decimal? _Cf_F1_Ven; public decimal? Cf_F1_Ven { get { return _Cf_F1_Ven; } set { Set(ref _Cf_F1_Ven, value, "Cf_F1_Ven"); } }
		private decimal? _Cf_D1_Sam; public decimal? Cf_D1_Sam { get { return _Cf_D1_Sam; } set { Set(ref _Cf_D1_Sam, value, "Cf_D1_Sam"); } }
		private decimal? _Cf_F1_Sam; public decimal? Cf_F1_Sam { get { return _Cf_F1_Sam; } set { Set(ref _Cf_F1_Sam, value, "Cf_F1_Sam"); } }
		private decimal? _Cf_D2_Lun; public decimal? Cf_D2_Lun { get { return _Cf_D2_Lun; } set { Set(ref _Cf_D2_Lun, value, "Cf_D2_Lun"); } }
		private decimal? _Cf_F2_Lun; public decimal? Cf_F2_Lun { get { return _Cf_F2_Lun; } set { Set(ref _Cf_F2_Lun, value, "Cf_F2_Lun"); } }
		private decimal? _Cf_D2_Mar; public decimal? Cf_D2_Mar { get { return _Cf_D2_Mar; } set { Set(ref _Cf_D2_Mar, value, "Cf_D2_Mar"); } }
		private decimal? _Cf_F2_Mar; public decimal? Cf_F2_Mar { get { return _Cf_F2_Mar; } set { Set(ref _Cf_F2_Mar, value, "Cf_F2_Mar"); } }
		private decimal? _Cf_D2_Mer; public decimal? Cf_D2_Mer { get { return _Cf_D2_Mer; } set { Set(ref _Cf_D2_Mer, value, "Cf_D2_Mer"); } }
		private decimal? _Cf_F2_Mer; public decimal? Cf_F2_Mer { get { return _Cf_F2_Mer; } set { Set(ref _Cf_F2_Mer, value, "Cf_F2_Mer"); } }
		private decimal? _Cf_D2_Jeu; public decimal? Cf_D2_Jeu { get { return _Cf_D2_Jeu; } set { Set(ref _Cf_D2_Jeu, value, "Cf_D2_Jeu"); } }
		private decimal? _Cf_F2_Jeu; public decimal? Cf_F2_Jeu { get { return _Cf_F2_Jeu; } set { Set(ref _Cf_F2_Jeu, value, "Cf_F2_Jeu"); } }
		private decimal? _Cf_D2_Ven; public decimal? Cf_D2_Ven { get { return _Cf_D2_Ven; } set { Set(ref _Cf_D2_Ven, value, "Cf_D2_Ven"); } }
		private decimal? _Cf_F2_Ven; public decimal? Cf_F2_Ven { get { return _Cf_F2_Ven; } set { Set(ref _Cf_F2_Ven, value, "Cf_F2_Ven"); } }
		private decimal? _Cf_D2_Sam; public decimal? Cf_D2_Sam { get { return _Cf_D2_Sam; } set { Set(ref _Cf_D2_Sam, value, "Cf_D2_Sam"); } }
		private decimal? _Cf_F2_Sam; public decimal? Cf_F2_Sam { get { return _Cf_F2_Sam; } set { Set(ref _Cf_F2_Sam, value, "Cf_F2_Sam"); } }
		private decimal? _Prix_Tr_Est; public decimal? Prix_Tr_Est { get { return _Prix_Tr_Est; } set { Set(ref _Prix_Tr_Est, value, "Prix_Tr_Est"); } }
		private bool? _Inclu_Tr; public bool? Inclu_Tr { get { return _Inclu_Tr; } set { Set(ref _Inclu_Tr, value, "Inclu_Tr"); } }
		private bool? _Cornerpad; public bool? Cornerpad { get { return _Cornerpad; } set { Set(ref _Cornerpad, value, "Cornerpad"); } }
		private bool? _Pickup; public bool? Pickup { get { return _Pickup; } set { Set(ref _Pickup, value, "Pickup"); } }
		private bool? _Prixmsf; public bool? Prixmsf { get { return _Prixmsf; } set { Set(ref _Prixmsf, value, "Prixmsf"); } }
		private bool? _Fovalide; public bool? Fovalide { get { return _Fovalide; } set { Set(ref _Fovalide, value, "Fovalide"); } }
		private string _Tel1poste; public string Tel1poste { get { return _Tel1poste; } set { Set(ref _Tel1poste, value, "Tel1poste"); } }
		private string _Tel2poste; public string Tel2poste { get { return _Tel2poste; } set { Set(ref _Tel2poste, value, "Tel2poste"); } }
		private decimal? _Tvhtaux; public decimal? Tvhtaux { get { return _Tvhtaux; } set { Set(ref _Tvhtaux, value, "Tvhtaux"); } }
		private bool? _Paletreg; public bool? Paletreg { get { return _Paletreg; } set { Set(ref _Paletreg, value, "Paletreg"); } }

	}
}