//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI_RSS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_EDI_RSS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_EDI_RSS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EDI_RSS.Resource_EDI_RSS", typeof(Resource_EDI_RSS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos; &apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;
        ///&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos;&gt;&lt;meta http-equiv=&apos;Content-Language&apos; content=&apos;fr-ca&apos;&gt;
        ///		&lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;/&gt;
        ///		&lt;title&gt;Validation email&lt;/title&gt;
        ///		
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt; 
        ///			  table {border-collapse:separate;}
        ///			  a, a:l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template810Email {
            get {
                return ResourceManager.GetString("template810Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos; &apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;
        ///&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos;&gt;&lt;meta http-equiv=&apos;Content-Language&apos; content=&apos;fr-ca&apos;&gt;
        ///		&lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;/&gt;
        ///		&lt;title&gt;Validation email&lt;/title&gt;
        ///		
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt; 
        ///			  table {border-collapse:separate;}
        ///			  a, a:l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template855Email {
            get {
                return ResourceManager.GetString("template855Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &apos;-//W3C//DTD XHTML 1.0 Transitional//EN&apos; &apos;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&apos;&gt;
        ///&lt;html xmlns=&apos;http://www.w3.org/1999/xhtml&apos;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=utf-8&apos;&gt;&lt;meta http-equiv=&apos;Content-Language&apos; content=&apos;fr-ca&apos;&gt;
        ///		&lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;/&gt;
        ///		&lt;title&gt;Validation email&lt;/title&gt;
        ///		
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt; 
        ///			  table {border-collapse:separate;}
        ///			  a, a:l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template856Email {
            get {
                return ResourceManager.GetString("template856Email", resourceCulture);
            }
        }
    }
}
